#theme = "Dracula"

[colors.bright]
black = "#575b70"
blue = "#b289fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.cursor]
cursor = "#FFFFFF"
text = "#3B4252"

[colors.normal]
black = "#575b70"
blue = "#6B5297"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

#[colors.normal]
#black = "#000000"
#blue = "#caa9fa"
#cyan = "#8be9fd"
#green = "#50fa7b"
#magenta = "#ff79c6"
#red = "#ff5555"
#white = "#bfbfbf"
#yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[cursor]
style = {shape = "Underline", blinking = "Always"}
vi_mode_style = {shape = "Underline", blinking = "Always"}
thickness = 0.25

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 10.5

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"

[mouse]
hide_when_typing = true

[window.padding]
x = 7
y = 8

[general]
