#theme = "Dracula"

[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'


[colors.normal]
black =   '#000000'
red =     '#ff5555'
green =   '#50fa7b'
yellow =  '#f1fa8c'
blue =    '#6B5297'
magenta = '#ff79c6'
cyan =    '#8be9fd'
white =   '#ffffff'



[colors.bright]
black =   '#575b70'
red =     '#ff6e67'
green =   '#5af78e'
yellow =  '#f4f99d'
blue =    '#b289fa'
magenta = '#ff92d0'
cyan =    '#9aedfe'
white =   '#ffffff'


#[colors.normal]
#black = "#000000"
#blue = "#caa9fa"
#cyan = "#8be9fd"
#green = "#50fa7b"
#magenta = "#ff79c6"
#red = "#ff5555"
#white = "#bfbfbf"
#yellow = "#f1fa8c"


[cursor]
style = {shape = "Underline", blinking = "Always"}
vi_mode_style = {shape = "Underline", blinking = "Always"}
thickness = 0.25

[colors.cursor]
cursor = "#FFFFFF"
text = "#3B4252"


[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"

[mouse]
hide_when_typing = true

[window.padding]
x = 7
y = 8

[general]
