#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI
bspc monitor -d I II III

bspc config border_width		2
bspc config window_gap			3

bspc config split_ratio          0.5
bspc config center_pseudo_tiled   true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config normal_border_color "#282A36"
#bspc config normal_border_color "#6B5297"
bspc config focused_border_color  "#1E1F29"
#bspc config focused_border_color  "#6B5297"


bspc rule -a "VirtualBox Manager" desktop='^3' follow=on
bspc rule -a "VirtualBox" desktop='^3' follow=on state=floating

bspc rule -a "Virt-manager" desktop='^3' follow=on
bspc rule -a "mpv" desktop='^3' follow=on #state=floating 
bspc rule -a "wps" desktop='^3' follow=on
bspc rule -a "Pcmanfm" desktop='^3'	follow=on state=floating
bspc rule -a "Nemo" desktop='^3'	follow=on
bspc rule -a "Brave-browser" desktop='^2' follow=on focus=on
bspc rule -a "Cromite" desktop='^2' follow=on focus=on
bspc rule -a "Alacritty" desktop='^1' follow=on
bspc rule -a "mplayer2" state=floating
bspc rule -a "Viewnior" state=floating
bspc rule -a "SVPManager" desktop='^4'state=floating
bspc rule -a "Kupfer.py" focus=on
bspc rule -a "Screenkey" manage=off

xsetroot -cursor_name left_ptr &
/usr/bin/bash ~/.config/polybar/launch.sh --blocks 
